package solenetech.ao.credit.core.service;

import io.camunda.zeebe.client.ZeebeClient;
import jakarta.transaction.Transactional;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import solenetech.ao.credit.api.dtos.CreatCreditRequest;
import solenetech.ao.credit.core.entity.CreditRequest;
import solenetech.ao.credit.core.enuns.RequestStatus;
import solenetech.ao.credit.core.repository.CreditRequestRepository;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@AllArgsConstructor
@Service
public class CreditRequestService {
    private CreditRequestRepository creditRequestRepository;
    private final ZeebeClient zeebeClient;
    @Transactional
    public CreditRequest createCreditRequest(CreatCreditRequest creditRequest) {
        var CreditRequest = new CreditRequest(
                null,
                creditRequest.name(),
                creditRequest.income(),
                creditRequest.age(),
                RequestStatus.receveid,
                null

        );
        var savedCreditRequest = creditRequestRepository.save(CreditRequest);

        // Now the ID has been generated by JPA
        if (savedCreditRequest.getId() == null) {
            throw new RuntimeException("ID não foi gerado após salvar");
        }
        zeebeClient.newCreateInstanceCommand()
                .bpmnProcessId("Process_CreditApproval")
                .latestVersion()
                .variables(Map.of(
                        "creditRequestId", savedCreditRequest.getId().toString(),
                        "income", Double.valueOf(savedCreditRequest.getIncome()),
                        "age", Integer.valueOf(savedCreditRequest.getAge())
                ))
                .send()
                .join();
        return savedCreditRequest;
    }

    public List<CreditRequest> getAll() {
        return creditRequestRepository.findAll();
    }
    public CreditRequest getById(UUID id) {
        return creditRequestRepository.findById(id).get();
    }
}
